# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"
  config.hostmanager.enabled = true
  config.hostmanager.include_offline = true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end

  NodeCount = 3

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "kafka#{i}" do |c|
      c.vm.hostname = "kafka#{i}"
      c.vm.network "private_network", ip: "192.168.0.1#{i}"
    end
  end

  config.vm.provision "shell", path: "bootstrap.sh"

end
